name: Watch

on: [push]

jobs:
  docker:
    name: Update docker image with latest version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Fetch last version
        id: fetch_version
        run: |
          last=$(curl -s https://packagist.org/packages/phpstan/phpstan.json|jq '[.package.versions[]|select(.version|test("^\\d+\\.\\d+\\.\\d+$"))|.version]|max_by(.|[splits("[.]")]|map(tonumber))')
          echo "Last PHPStan version is $last"
          echo ::set-output name=last::$last

          sed -i -re "s/require phpstan\/phpstan [^\\]+/require phpstan\/phpstan $last/" Dockerfile
          cat Dockerfile
